name: ci/cd

on:
  workflow_dispatch:
  push:
    branches: [ main, 'release/*' ]
  pull_request:
    branches: [ main, 'release/*' ]
  # Build once a month, just to be sure things are still working
  schedule:
    - cron: "19 3 26 * *"

jobs:

  builds:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: ['26', '25', '24', '25', '26', '27']

    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.22'
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    #- name: Dialyzer
    #  run: rebar3 dialyzer
    #- name: Proper Tests
    #  run: rebar3 as test do compile, proper --regressions
    #- name: Run Unit Tests
    #  run: rebar3 as test lfe ltest -tall
    - name: Run Common Tests
      run: rebar3 ct -v